include ./ocaml_basic.gmk

test::
	ocaml < runTest.ml

all:: item.cmo ordered.cmo \
      smallStream.cmo \
      rqueue.cmo realTimeQueue.cmo \
      heap.cmo scheduledBinomialHeap.cmo \
      sortable.cmo scheduledBottomUpMergeSort.cmo

